/**
 * Banned item list.
 * @type {Record<string, import('./_configtypes.js').CONF_bannedItemData>}
 */
export const bannedItemList: Record<string, CONF_bannedItemData> = {
    // Commonly banned
    'minecraft:acacia_standing_sign': {},
    'minecraft:acacia_wall_sign': {},
    'minecraft:birch_standing_sign': {},
    'minecraft:birch_wall_sign': {},
    'minecraft:bubble_column': {},
    'minecraft:camera': {},
    'minecraft:crimson_double_slab': {},
    'minecraft:crimson_standing_sign': {},
    'minecraft:crimson_wall_sign': {},
    'minecraft:darkoak_standing_sign': {},
    'minecraft:darkoak_wall_sign': {},
    'minecraft:debug_stick': {},
    'minecraft:double_stone_block_slab': {},
    'minecraft:double_wooden_slab': {},
    'minecraft:end_gateway': {},
    'minecraft:end_portal': {},
    'minecraft:fire': {},
    'minecraft:flowing_lava': {},
    'minecraft:flowing_water': {},
    'minecraft:glowingobsidian': {},
    'minecraft:info_update': {},
    'minecraft:info_update2': {},
    'minecraft:invisible_bedrock': {},
    'minecraft:item.acacia_door': {},
    'minecraft:item.bed': {},
    'minecraft:item.beetroot': {},
    'minecraft:item.birch_door': {},
    'minecraft:item.cake': {},
    'minecraft:item.camera': {},
    'minecraft:item.campfire': {},
    'minecraft:item.cauldron': {},
    'minecraft:item.chain': {},
    'minecraft:item.crimson_door': {},
    'minecraft:item.dark_oak_door': {},
    'minecraft:item.flower_pot': {},
    'minecraft:item.frame': {},
    'minecraft:item.hopper': {},
    'minecraft:item.iron_door': {},
    'minecraft:item.jungle_door': {},
    'minecraft:item.kelp': {},
    'minecraft:item.nether_wart': {},
    'minecraft:item.reeds': {},
    'minecraft:item.spruce_door': {},
    'minecraft:item.warped_door': {},
    'minecraft:item.wheat': {},
    'minecraft:item.wooden_door': {},
    'minecraft:jungle_standing_sign': {},
    'minecraft:jungle_wall_sign': {},
    'minecraft:lava': {},
    'minecraft:lit_blast_furnace': {},
    'minecraft:lit_furnace': {},
    'minecraft:lit_redstone_lamp': {},
    'minecraft:lit_smoker': {},
    'minecraft:melon_stem': {},
    'minecraft:moving_block': {},
    'minecraft:netherreactor': {},
    'minecraft:piston_arm_collision': {},
    'minecraft:portal': {},
    'minecraft:powered_comparator': {},
    'minecraft:powered_repeater': {},
    'minecraft:pumpkin_stem': {},
    'minecraft:redstone_wire': {},
    'minecraft:reserved6': {},
    'minecraft:soul_fire': {},
    'minecraft:spruce_standing_sign': {},
    'minecraft:spruce_wall_sign': {},
    'minecraft:stonecutter': {},
    'minecraft:unknown': {},
    'minecraft:unlit_redstone_torch': {},
    'minecraft:unpowered_comparator': {},
    'minecraft:unpowered_repeater': {},
    'minecraft:wall_banner': {},
    'minecraft:wall_sign': {},
    'minecraft:warped_double_slab': {},
    'minecraft:warped_standing_sign': {},
    'minecraft:warped_wall_sign': {},
    'minecraft:water': {},

    // Required OP
    'minecraft:agent_spawn_egg': {},
    'minecraft:allow': {},
    'minecraft:barrier': {},
    'minecraft:bedrock': {},
    'minecraft:border_block': {},
    'minecraft:chain_command_block': {},
    'minecraft:command_block': {},
    'minecraft:command_block_minecart': {},
    'minecraft:deny': {},
    'minecraft:jigsaw': {},
    'minecraft:light_block': {},
    'minecraft:npc_spawn_egg': {},
    'minecraft:repeating_command_block': {},
    'minecraft:structure_void': {},
    'minecraft:mob_spawner': {},
}
Object.setPrototypeOf(bannedItemList, null)



import { CONF_bannedItemData } from "./_configtypes.js"
