particle minecraft:end_chest  ~1 ~1 ~1
particle minecraft:end_chest  ~1 ~1 ~-1
particle minecraft:end_chest  ~-1 ~1 ~1
particle minecraft:end_chest  ~-1 ~1 ~-1
particle minecraft:end_chest  ~1 ~2 ~1
particle minecraft:end_chest  ~1 ~2 ~-1
particle minecraft:end_chest  ~-1 ~2 ~1
particle minecraft:end_chest  ~-1 ~2 ~-1
particle minecraft:end_chest  ~1 ~1 ~1
particle minecraft:end_chest  ~1 ~1 ~-1
particle minecraft:end_chest  ~-1 ~1 ~1
particle minecraft:end_chest  ~-1 ~1 ~-1
particle minecraft:end_chest  ~1 ~2 ~1
particle minecraft:end_chest  ~1 ~2 ~-1
particle minecraft:end_chest  ~-1 ~2 ~1
particle minecraft:end_chest  ~-1 ~2 ~-1
particle minecraft:end_chest  ~1 ~1 ~1
particle minecraft:end_chest  ~1 ~1 ~-1
particle minecraft:end_chest  ~-1 ~1 ~1
particle minecraft:end_chest  ~-1 ~1 ~-1
particle minecraft:end_chest  ~1 ~2 ~1
particle minecraft:end_chest  ~1 ~2 ~-1
particle minecraft:end_chest  ~-1 ~2 ~1
particle minecraft:end_chest  ~-1 ~2 ~-1